### PR TITLE
Adds new singularity

### PR DESCRIPTION
**Pull request by FourIsTheNumber**
Gangue singularity that can be made in the black hole compressor

### CODE REVIEW

**Comment by Reflex18** [comment]
Is this just a meme?

**Review by NotAPenguin0 — APPROVED** [review]
Gangueing

**Comment by chochem** [comment]
hmm, how do you ensure that people produce it while ensuring there is no semblence of usefulness?

**Comment by Reflex18** [comment]
> hmm, how do you ensure that people produce it while ensuring there is no semblence of usefulness?

Depending on how hard it is to create a trophy, there could be a Gangue singularity trophy granted on holding the item. Therefore it ensures no real gameplay use but provides the player with a neat trophy.

**Pull request merged**
